name: 'rf360_dwh'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory to store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
    - "target"
    - "dbt_packages"

quoting:
  database: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# By default, all models in staging/directory are built as views and all marts/directory
# are built as tables. These settings can be overridden in the individual model files
# using the '{{ config(...) }}' macro.

models:
  rf360_dwh:
    staging:
      sap:
        +materialized: view
    marts:
      +materialized: table
      +tags: daily_update
